// RAG service for the Rights chat.
// - Lazily builds a per-doc embedding index (loads pre-built JSON if present).
// - Retrieves top-k docs by cosine similarity.
// - Falls back to BM25-ish keyword overlap when embeddings are unavailable
//   (offline + missing pre-built index).
import { RIGHTS_DOCS, RightsDoc, buildRightsContext } from '../data/rights';
import { embed } from './sarvam';

// Pre-built embeddings (optional — generated by scripts/build-embeddings.mjs).
// The require is wrapped in try/catch so a missing file doesn't break the app.
let prebuilt: Record<string, number[]> | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  prebuilt = require('../data/rights.embeddings.json') as Record<string, number[]>;
} catch {
  prebuilt = null;
}

let runtimeIndex: Record<string, number[]> | null = null;
let indexBuildPromise: Promise<void> | null = null;

/** Cosine similarity for two equal-length numeric vectors. */
export function cosine(a: number[], b: number[]): number {
  if (!a.length || !b.length || a.length !== b.length) return 0;
  let dot = 0;
  let ma = 0;
  let mb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    ma += a[i] * a[i];
    mb += b[i] * b[i];
  }
  const denom = Math.sqrt(ma) * Math.sqrt(mb);
  return denom === 0 ? 0 : dot / denom;
}

/** Build embeddings for all RIGHTS_DOCS at boot if no prebuilt index. */
async function ensureIndex(): Promise<void> {
  if (prebuilt && Object.keys(prebuilt).length === RIGHTS_DOCS.length) {
    runtimeIndex = prebuilt;
    return;
  }
  if (runtimeIndex) return;
  if (indexBuildPromise) return indexBuildPromise;
  indexBuildPromise = (async () => {
    const idx: Record<string, number[]> = {};
    for (const d of RIGHTS_DOCS) {
      try {
        idx[d.id] = await embed(`${d.title}\n${d.hi}\n${d.summary}`);
      } catch {
        // hashEmbed fallback in embed() should keep us from getting here.
      }
    }
    runtimeIndex = idx;
  })();
  return indexBuildPromise;
}

/** Tokenize a query into lowercase word stems for the BM25-ish fallback. */
function tokens(s: string): string[] {
  return s
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]+/gu, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 1);
}

/** Keyword-overlap fallback when embeddings are unusable. */
function keywordRank(query: string, k: number): RightsDoc[] {
  const q = tokens(query);
  const scored = RIGHTS_DOCS.map((d) => {
    const docTokens = new Set(tokens(`${d.title} ${d.hi} ${d.summary}`));
    let score = 0;
    for (const t of q) if (docTokens.has(t)) score += 1;
    return { d, score };
  });
  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, k)
    .filter((s) => s.score > 0)
    .map((s) => s.d);
}

/**
 * Retrieve top-k Rights docs most relevant to `query`.
 * Tries embeddings + cosine; falls back to keyword overlap; finally to all docs.
 */
export async function retrieveRights(query: string, k = 3): Promise<RightsDoc[]> {
  try {
    await ensureIndex();
    const idx = runtimeIndex;
    if (!idx) throw new Error('no index');
    const qv = await embed(query);
    const ranked = RIGHTS_DOCS.map((d) => ({ d, s: cosine(qv, idx[d.id] ?? []) }))
      .sort((a, b) => b.s - a.s)
      .slice(0, k)
      .map((r) => r.d);
    if (ranked.length) return ranked;
  } catch (e) {
    console.warn('[rag.retrieveRights] embedding path failed:', e);
  }
  const kw = keywordRank(query, k);
  if (kw.length) return kw;
  // Last resort — first k docs so we always return something.
  return RIGHTS_DOCS.slice(0, k);
}

// Re-export so callers can compose context without importing two modules.
export { buildRightsContext };
